import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatFormFieldModule, MatInputModule } from '@angular/material';
import { ScrollingModule } from '@angular/cdk/scrolling';
import { LayoutModule } from '@angular/cdk/layout';
import {
  MatExpansionModule,
  MatIconModule,
  MatListModule,
  MatMenuModule,
  MatSidenavModule,
  MatToolbarModule,
  MatDialogModule,
  MatCardModule,
  MatSelectModule,
  MatButtonModule,
  MatTabsModule,
  MatBadgeModule,
  MatGridListModule,
  MatOptionModule,
  MatAutocompleteModule,
  MatProgressBarModule,
  MatDatepickerModule,
  MatRadioModule,
  MatTooltipModule,
  MatPaginatorModule,
  MatChipsModule,
  MatSnackBarModule,
} from '@angular/material';
import {
  FaIconLibrary,
  FontAwesomeModule,
} from '@fortawesome/angular-fontawesome';
import {
  faCog,
  faBars,
  faRocket,
  faPowerOff,
  faUserCircle,
  faPlayCircle,
  faHome,
  faBriefcase,
  faBurn,
  faUser,
  faUserAstronaut,
  faBlog,
  faChessBoard,
  faIdCard,
  faExternalLinkAlt,
} from '@fortawesome/free-solid-svg-icons';
import { faCopy, faCopyright } from '@fortawesome/free-regular-svg-icons';
import {
  faGithub,
  faMediumM,
  faTwitter,
  faInstagram,
  faLinkedin,
  faYoutube,
  faAngular,
  faReact,
  faHtml5,
  faJava,
  faPython,
  faDocker,
  faNodeJs,
  faJs,
  faGitAlt,
  faTelegram,
} from '@fortawesome/free-brands-svg-icons';
import { ParticlesModule } from 'angular-particle';

@NgModule({
  imports: [
    CommonModule,
    ParticlesModule,
    FormsModule,
    MatFormFieldModule,
    MatInputModule,
    LayoutModule,
    MatToolbarModule,
    MatSidenavModule,
    MatIconModule,
    MatMenuModule,
    MatListModule,
    MatExpansionModule,
    MatDialogModule,
    MatCardModule,
    MatButtonModule,
    MatSelectModule,
    MatTabsModule,
    MatDatepickerModule,
    MatBadgeModule,
    MatOptionModule,
    MatGridListModule,
    MatAutocompleteModule,
    MatProgressBarModule,
    MatRadioModule,
    MatTooltipModule,
    MatPaginatorModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatChipsModule,
    MatSnackBarModule,
    ScrollingModule,
    FontAwesomeModule,
  ],
  exports: [
    FormsModule,
    ParticlesModule,
    MatFormFieldModule,
    MatInputModule,
    LayoutModule,
    MatToolbarModule,
    MatSidenavModule,
    MatIconModule,
    MatMenuModule,
    MatListModule,
    MatDatepickerModule,
    MatExpansionModule,
    MatDialogModule,
    MatCardModule,
    MatSelectModule,
    MatButtonModule,
    MatOptionModule,
    MatTabsModule,
    MatBadgeModule,
    MatGridListModule,
    MatAutocompleteModule,
    MatProgressBarModule,
    MatRadioModule,
    MatTooltipModule,
    MatPaginatorModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatChipsModule,
    MatSnackBarModule,
    ScrollingModule,
    FontAwesomeModule,
  ],
})
export class SharedModule {
  constructor(faIconLibrary: FaIconLibrary) {
    faIconLibrary.addIcons(
      faCog,
      faBars,
      faLinkedin,
      faRocket,
      faPowerOff,
      faUserCircle,
      faPlayCircle,
      faGithub,
      faMediumM,
      faTwitter,
      faInstagram,
      faYoutube,
      faAngular,
      faReact,
      faHtml5,
      faJava,
      faPython,
      faDocker,
      faNodeJs,
      faJs,
      faGitAlt,
      faCopyright,
      faExternalLinkAlt,
      faHome,
      faBriefcase,
      faBurn,
      faUser,
      faUserAstronaut,
      faBlog,
      faChessBoard,
      faIdCard,
      faTelegram,
      faCopy,
    );
  }
}
